-- MySQL Script generated by MySQL Workbench
-- Sun Jan 12 01:43:58 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema stockmanagement_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `stockmanagement_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `stockmanagement_db` ;

-- -----------------------------------------------------
-- Table `stockmanagement_db`.`stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stockmanagement_db`.`stock` (
  `id` INT AUTO_INCREMENT NOT NULL,
  `stock_price` DOUBLE NOT NULL,
  `stock_quantity` INT NOT NULL,
  `stock_category` VARCHAR(100) NULL DEFAULT NULL,
  `stock_name` VARCHAR(100) NOT NULL,
  `stock_code` VARCHAR(255) NULL DEFAULT NULL,
  `stock_photo_path` VARCHAR(255) NULL DEFAULT NULL,
  `stock_description` LONGTEXT NULL DEFAULT NULL,
  `stock_status` ENUM('AVAILABLE', 'OUT_OF_STOCK') NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UKeymtnhbc6bg0o6q9i4k5a7phr` (`stock_code` ASC) VISIBLE
) ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `stockmanagement_db`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stockmanagement_db`.`user` (
  `id` INT AUTO_INCREMENT NOT NULL,
  `username` VARCHAR(20) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UKsb8bbouer5wak8vyiiy4pf2bx` (`username` ASC) VISIBLE
) ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `stockmanagement_db`.`user_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stockmanagement_db`.`user_roles` (
  `user_id` INT NOT NULL,
  `role` ENUM('ROLE_ADMIN', 'ROLE_CUSTOMER') NULL DEFAULT NULL,
  INDEX `FK55itppkw3i07do3h7qoclqd4k` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FK55itppkw3i07do3h7qoclqd4k`
    FOREIGN KEY (`user_id`)
    REFERENCES `stockmanagement_db`.`user` (`id`)
) ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;
